---
title: 10.3.1 使用throws声明抛出异常
categories: 
  - 1 疯狂Java讲义 (第4版)
  - 第10章 异常处理
  - 10.3 Checked异常和Runtime异常体系
abbrlink: d5e8f6ca
date: 2019-07-13 17:22:50
updated: 2022-04-03 01:21:14
---
# 10.3.1 使用throws声明抛出异常 #
使用`throws`声明抛出异常的思路是,当前方法不知道如何处理这种类型的异常,该异常应该由上级调用者处理;
如果`main`方法也不知道如何处理这种类型的异常,也可以使用`throws`声明抛出异常,该异常将交给`JVM`处理。
**`JVM`对异常的处理方法是,打印异常的跟踪栈信息,并中止程序运行**,这就是前面程序在遇到异常后自动结束的原因。

## 在方法签名中使用throws声明抛出异常 ##
**`throws`声明抛出只能在`方法签名`中使用**,`throws`可以声明抛出多个异常类,多个异常类之间以逗号隔开。

**`throws`声明抛出的语法格式仅跟在方法签名之**后,如下例子程序使用了`throws`来声明抛出`IOException`异常,**一旦使用`throws`语句声明抛出该异常,程序就无须使用`try-catch`块来捕获该异常了**。
```java
import java.io.*;

public class ThrowsTest
{
    public static void main(String[] args)
        throws IOException
    {
        FileInputStream fis = new FileInputStream("a.txt");
    }
}
```
上面程序声明不处理`IOException`异常,将该异常交给`JVM`处理,所以程序一旦遇到该异常,`JVM`就会打印该异常的跟踪栈信息,并结束程序。运行上面程序,效果如下所示:
```cmd
Exception in thread "main" java.io.FileNotFoundException: a.txt (系统找不到指定的文件。)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at ThrowsTest.main(ThrowsTest.java:8)
```
如果某段代码中调用了一个带`throws`声明的方法,该方法声明抛出了`Checked`异常,则表明该方法希望它的调用者来处理该异常。也就是说,调用该方法时要么放在`try`块中显式捕获该异常,要么放在另一个带`throws`声明抛出的方法中。如下例子程序示范了这种用法。
```java
import java.io.*;

public class ThrowsTest2
{
    public static void main(String[] args) throws Exception
    {
        // 因为test()方法声明抛出IOException异常，
        // 所以调用该方法的代码要么处于try...catch块中，
        // 要么处于另一个带throws声明抛出的方法中。
        test();
    }
    public static void test() throws IOException
    {
        // 因为FileInputStream的构造器声明抛出IOException异常，
        // 所以调用FileInputStream的代码要么处于try...catch块中，
        // 要么处于另一个带throws声明抛出的方法中。
        FileInputStream fis = new FileInputStream("a.txt");
    }
}
```
